package tech.buildrun.orderms.listener.dto;

import java.math.BigDecimal;

public record ItemEvent(String produto, Integer quantidade, BigDecimal preco) {
    // Constructor and getters are automatically generated by the record keyword{

}
