package tech.buildrun.orderms.listener.dto;

import java.util.List;

public record OrderCreatedEvent(Long codigoPedido, Long codigoCliente, List<ItemEvent> itens) {
    // Constructor and getters are automatically generated by the record keyword

}
